# Generated by Django 4.2.7 on 2025-11-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('veiculos', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('descricao_problema', models.TextField(blank=True, verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clientes.cliente')),
                ('mecanico', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['mecanico', 'gerente', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='core.usuario')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
