# Generated by Django 4.2.7 on 2025-11-23 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('placa', models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Placa deve estar no formato ABC1234 ou ABC1D23 (Mercosul)', regex='^[A-Z]{3}\\d{4}$|^[A-Z]{3}\\d[A-Z]\\d{2}$')], verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('cor', models.CharField(blank=True, max_length=30, verbose_name='Cor')),
                ('chassis', models.CharField(blank=True, max_length=17, verbose_name='Chassi')),
                ('status', models.CharField(choices=[('em_uso', 'Em Uso'), ('em_manutencao', 'Em Manutenção'), ('descartado', 'Descartado')], default='em_uso', max_length=20, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
