# Generated by Django 4.2.7 on 2025-11-23 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='CPF/CNPJ deve conter entre 11 e 14 dígitos numéricos', regex='^\\d{11,14}$')], verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
